---
kind: pipeline
name: default


steps:
  - name: pylava
    image: snakepacker/python:all
    pull: always
    commands:
      - tox
    environment:
      TOXENV: pylava

  - name: checkdoc
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: checkdoc

  - name: python 3.5
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py35
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.6
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.7
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.7 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: uvloop37
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.8
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py38
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.8 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: uvloop38
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.9
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: py39
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.9 uvloop
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: uvloop39
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: python 3.6 contextvars
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: contextvars36
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

  - name: RPC example
    image: snakepacker/python:all
    depends_on:
      - linter
    pull: always
    commands:
      - tox
    environment:
      TOXENV: rpc
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_TOKEN

---
kind: signature
hmac: ad7b3be9cc94ae4ac82a5c28c1a48bc82dab11a51d502d66d150e2fe76cc9680

...
