version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    post_install:
      - $READTHEDOCS_VIRTUALENV_PATH/bin/pip install poetry
      - $READTHEDOCS_VIRTUALENV_PATH/bin/poetry config virtualenvs.create false
      - $READTHEDOCS_VIRTUALENV_PATH/bin/poetry env info
      - $READTHEDOCS_VIRTUALENV_PATH/bin/poetry install --all-extras

formats:
  - pdf
  - epub
