version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry env info
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-extras

formats:
  - pdf
  - epub
