# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - pylava
          - checkdoc
          - mypy

    steps:
      - uses: actions/checkout@v2
      - name: tox ${{ matrix.linter }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.linter }}
        with:
          args: tox

  tests:
    needs: lint
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: docker://mosquito/aiormq-rabbitmq
        ports:
          - 5672:5672

    strategy:
      fail-fast: false

      matrix:
        toxenv:
          - py35
          - py36
          - py37
          - py38
          - py39
          - uvloop37
          - uvloop38
          - uvloop39
          - contextvars36
          - rpc
          - rpc_udp

    steps:
      - uses: actions/checkout@v2

      - name: tox ${{ matrix.toxenv }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.toxenv }}
          AMQP_URL: amqp://guest:guest@rabbitmq
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          args: /bin/bash -c "wait-for-port rabbitmq:5672 && tox"
