# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - pylava
          - checkdoc
          - mypy
          - pydoc

    steps:

      - uses: actions/checkout@v2

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install tox
        run: python -m pip install tox

      - name: Prepare tox env
        run: tox --notest
        env:
          TOXENV: ${{ matrix.linter }}

      - name: Run ${{ matrix.linter }}
        run: tox
        env:
          FORCE_COLOR: yes
          TOXENV: ${{ matrix.linter }}

  tests:
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - python: '3.6'
            toxenv: py36
            os: ubuntu-latest
          - python: '3.7'
            toxenv: py37
            os: ubuntu-latest
          - python: '3.8'
            toxenv: py38
            os: ubuntu-latest
          - python: '3.9'
            toxenv: py39
            os: ubuntu-latest
          - python: '3.10'
            toxenv: py310
            os: ubuntu-latest
          - python: '3.10'
            toxenv: rpc
            os: ubuntu-latest
          - python: '3.10'
            toxenv: rpc_udp
            os: ubuntu-latest
          - python: '3.6'
            toxenv: contextvars36
            os: ubuntu-latest
          - python: '3.7'
            toxenv: uvloop37
            os: ubuntu-latest
          - python: '3.8'
            toxenv: uvloop38
            os: ubuntu-latest
          - python: '3.9'
            toxenv: uvloop39
            os: ubuntu-latest

# TODO: Fix builds and enable it
#          - python: '3.6'
#            toxenv: py36
#            os: macos-latest
#          - python: '3.7'
#            toxenv: py37
#            os: macos-latest
#          - python: '3.8'
#            toxenv: py38
#            os: macos-latest
#          - python: '3.9'
#            toxenv: py39
#            os: macos-latest
#          - python: '3.8'
#            toxenv: rpc
#            os: macos-latest
#          - python: '3.8'
#            toxenv: rpc_udp
#            os: macos-latest
#          - python: '3.6'
#            toxenv: contextvars36
#            os: macos-latest
#          - python: '3.7'
#            toxenv: uvloop37
#            os: macos-latest
#          - python: '3.8'
#            toxenv: uvloop38
#            os: macos-latest
#          - python: '3.9'
#            toxenv: uvloop39
#            os: macos-latest

#          - python: '3.6'
#            toxenv: py36
#            os: windows-latest
#          - python: '3.7'
#            toxenv: py37
#            os: windows-latest
#          - python: '3.8'
#            toxenv: py38
#            os: windows-latest
          - python: '3.9'
            toxenv: py39
            os: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: python -m pip install tox

      - name: Prepare tox env
        run: tox --notest
        env:
          TOXENV: ${{ matrix.toxenv }}

      - name: Run tox
        run: tox
        env:
          COVERALLS_PARALLEL: 'true'
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: yes
          TOXENV: ${{ matrix.toxenv }}

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
